apiVersion: v1
kind: Namespace
metadata:
  name: calico-isolation

---

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
    app: busybox
    name: kali1
  name: poda
  namespace: calico-isolation
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - ls; sleep 15780000
    image: zcbarnes1298/autodockerfile1
    imagePullPolicy: Always
    name: poda1
  - args:
    - /bin/sh
    - -c
    - ls; sleep 15780000
    image: zcbarnes1298/autodockerfile1
    imagePullPolicy: Always
    name: poda2
  - args:
    - /bin/sh
    - -c
    - ls; sleep 15780000
    image: zcbarnes1298/autodockerfile1
    imagePullPolicy: Always
    name: poda3
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/os: linux

---

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
    app: busybox
    name: kali2
  name: podb
  namespace: calico-isolation
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - ls; sleep 15780000
    image: zcbarnes1298/autodockerfile1
    imagePullPolicy: Always
    name: podb1
  - args:
    - /bin/sh
    - -c
    - ls; sleep 15780000
    image: zcbarnes1298/autodockerfile1
    imagePullPolicy: Always
    name: podb2
  - args:
    - /bin/sh
    - -c
    - ls; sleep 15780000
    image: zcbarnes1298/autodockerfile1
    imagePullPolicy: Always
    name: podb3
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/os: linux

---

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
    app: busybox
    name: kali3
  name: podc
  namespace: calico-isolation
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - ls; sleep 15780000
    image: zcbarnes1298/autodockerfile1
    imagePullPolicy: Always
    name: podc1
  - args:
    - /bin/sh
    - -c
    - ls; sleep 15780000
    image: zcbarnes1298/autodockerfile1
    imagePullPolicy: Always
    name: podc2
  - args:
    - /bin/sh
    - -c
    - ls; sleep 15780000
    image: zcbarnes1298/autodockerfile1
    imagePullPolicy: Always
    name: podc3
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/os: linux

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: denycomms
  namespace: calico-isolation
spec:
  podSelector: {}
  policyTypes:
  - Ingress
